### ISSUE TITLE
[ ] as command argument, and = in ' string, causes incorrect highlight

### ISSUE THREAD

**Issue by psprint** [chrisbra/vim-zsh#10]
Following code isn't highlighted correctly, when opened from `test.zsh` file:

```zsh
#!/bin/zsh
call ZUI[my_select_data] 'ZUI[my_host_data]='
if (( 1 )); then
    :
fi
```
It looks like following: [Asciinema](https://asciinema.org/a/87wlyoz4gsqgmone1jupjbaaj), [Imgur](http://imgur.com/a/pWrT8) – the `if (( ...` is higlighted as if it was inside a string.

**Comment by blueyed** [comment]
Happens with the following already:
```zsh
#!/bin/zsh
foo[bar] 'baz]='
shouldnotbeastring
```

**Comment by chrisbra** [comment]
please check that this is works as intended. When I get a positive feedback, will submit to Bram.

**Comment by psprint** [comment]
Sorry for a delay, I wanted to code something to see if this or other problem will occur. And that didn't happen, so I confirm the patch is working.

**Comment by psprint** [comment]
I've found something that breaks:

```zsh
if [[ "$1" = (#b)(ssh|git|http|https|ftp|ftps|rsync)://([a-zA-Z./_~-]##) ]]; then
fi
```

in this code what's after `#` will be highlighted as comment. Without the patch it is highlighted correctly.

**Comment by chrisbra** [comment]
It looks wrong for me with the previous version as well. What is the `##` doing?
Does that patch fix it:
```patch
diff --git a/syntax/zsh.vim b/syntax/zsh.vim
index c2ec84e..657e6ae 100644
--- a/syntax/zsh.vim
+++ b/syntax/zsh.vim
@@ -24,7 +24,7 @@ endif

 syn keyword zshTodo             contained TODO FIXME XXX NOTE

-syn region  zshComment          oneline start='\%(^\|\s*\)#' end='$'
+syn region  zshComment          oneline start='\%(^\|\s\+\)#' end='$'
                                 \ contains=zshTodo,@Spell fold

 syn region  zshComment          start='^\s*#' end='^\%(\s*#\)\@!'
```

**Comment by psprint** [comment]
You saying that it's wrong also without the patch lead me to try vim 8. And it indeed colorizes wrong. OS X vim 7.3 highlights correctly. The last patch does the fixing, checked both vim versions.
