### ISSUE TITLE
zshOptions should check for a preceding (un)setopt

### ISSUE THREAD

**Issue by anntzer** [chrisbra/vim-zsh#11]
Currently, zshOptions is declared as a keyword syntax element.  This means that a word such as "emacs" or "vi" will always be highlighted as an option, even though it is much more likely to be a normal command.

It should be possible e.g. to change zshOptions to be a match element that checks for the presence of a preceding setopt.

**Comment by chrisbra** [comment]
PR appreciated.

**Comment by chrisbra** [comment]
okay please check current head

**Comment by anntzer** [comment]
thanks!
