### ISSUE TITLE
Syntax support for alternate form of complex commands

### ISSUE THREAD

**Issue by kutsan** [chrisbra/vim-zsh#15]
Pipe symbol `|` shows the cursor position in Insert mode.

#### Before pressing enter

```sh
function something() {
    if () {
        # ...
    } else {|}
}
```

#### Current unexpected result after pressing enter

```sh
function something() {
    if () {
        # ...
    } else {
    |
}
}
```

#### Expected result after pressing enter

```sh
function something() {
    if () {
        # ...
    } else {
        |
    }
}
```

I think [alternate form of complex commands](http://zsh.sourceforge.net/Doc/Release/Shell-Grammar.html#Alternate-Forms-For-Complex-Commands) are not supported yet. Also, there are other cases where things get worse more than that.

**Comment by chrisbra** [comment]
Is this only about indenting? vim-zsh currently uses the indent script for the shell filetype, so this is to be expected.

**Comment by kutsan** [comment]
Yes, it's only about indenting.

**Comment by chrisbra** [comment]
Is this actually valid? Can you show an example please?

**Comment by kutsan** [comment]
I am not quite sure what you are talking about. What is valid? If you talking about the syntax, yes it is http://zsh.sourceforge.net/Doc/Release/Shell-Grammar.html#Alternate-Forms-For-Complex-Commands

**Comment by chrisbra** [comment]
Yes, please show me an example. I cannot guess from your syntax
