### ISSUE TITLE
Single quotes in trailing commas break syntax highlighting for rest of file

### ISSUE THREAD

**Issue by wincent** [chrisbra/vim-zsh#16]
As seen in this screen shot:

![sleep___glh-mbp___dot___vim__tmux_](https://user-images.githubusercontent.com/7074/34591501-dbe24432-f172-11e7-9019-4546f259b2a4.png)

Note the line where the highlighting goes bad:

```
setopt histignorespace      # don't record commands starting with a space
```

This only happens when a single quote is in the comment. It doesn't happen if the comment is on a line of its own.

For comparison, here is the same file with filetype 'sh':

![sleep___glh-mbp___dot___vim__tmux_](https://user-images.githubusercontent.com/7074/34591536-2303695e-f173-11e7-9476-f4194d7bdcb9.png)

This is with the runtime files that come with Neovim 0.2.1, but it also repros with Vim (tested v8.0 with patches 1-1350).

**Comment by chrisbra** [comment]
Yeah, the comment is not correctly seen after the options. I think this has been fixed in the latest version (tag: https://github.com/chrisbra/vim-zsh/releases/tag/20171122) which has been included in Vim here: https://github.com/vim/vim/commit/2f0584910c0ea93966dfa7b3b0272dfb16ea6f91

**Comment by wincent** [comment]
Confirmed fixed in updated version of Vim:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  3 2018 18:31:10)
macOS version
Included patches: 1-1400
Compiled by Homebrew
```

Thanks!
