### ISSUE TITLE
Broken syntax support for setopt in neovim

### ISSUE THREAD

**Issue by kutsan** [chrisbra/vim-zsh#19]
I'm not sure if it's Neovim's fault but this is what I get. The file is [here](https://github.com/kutsan/dotfiles/blob/cc39bd6ccd04403c79d4762fc942d8744392c265/.zsh/config/settings.zsh). I tried with `-u NONE` and it's still the same.

## Neovim

<img width="1070" alt="screen shot 2018-05-26 at 18 25 27" src="https://user-images.githubusercontent.com/10108377/40577682-403b147c-6112-11e8-956c-941ed7e8e31d.png">

## Vim

<img width="1053" alt="screen shot 2018-05-26 at 18 25 38" src="https://user-images.githubusercontent.com/10108377/40577684-46569d0e-6112-11e8-96c2-5f3bbb083853.png">

**Comment by chrisbra** [comment]
Yes neovim has most likely outdated runtime files. Check the header of syntax/zsh.vim. You can clone this repository to get more up to date versions. Most likely you are missing commit 8376ccb396cc8cf96b59041b4dae

**Comment by chrisbra** [comment]
also see neovim/neovim#7601

**Comment by kutsan** [comment]
@chrisbra Yeah looks like you are right, thanks for information! Do you know anything about the process, when they are going to sync runtime files. I'm going to clone this repository locally anyway but still I wonder.

**Comment by chrisbra** [comment]
No, the neovim guys merge runtime files updates once in a while. You might want to bug them however

**Comment by kutsan** [comment]
Thanks again. FYI I created an issue about that in neovim repository with issue number 8443.
