### ISSUE TITLE
Piping run-help to less breaks when using MANPAGER=vim -M +MANPAGER -

### ISSUE THREAD

**Issue by benknoble** [chrisbra/vim-zsh#25]
As the title says, with these settings piping the output of `run-help` to `less` is simply broken; nothing is readable. In particular, this is triggerable by the use of `K` or `:RunHelp ...` in a `zsh` file.

A temporary workaround exists (`setlocal keywordprg=:Man`, which I have placed in `~/.vim/after/ftplugin/zsh.vim`), but it doesn't include the use of `run-help` (which could be nice, particularly if one customizes `run-help` to do the right thing on builtins or aliases or functions.

Another workaround would be to redefine `:RunHelp` (using `:command!`) with whatever is desired.

**Comment by chrisbra** [comment]
I have never gotten `MANPAGER` to work, for me it always aborts with:

```
Vim: Error reading input, exiting...                                                                                                                                                                                                                            0,1           All
Vim: preserving files...
Vim: Finished.
man: command exited with status 1: sed -e '/^[[:space:]]*$/{ N; /....
```

It also aborts for a simple `vim < foobar.txt`
So how do I reproduce this case? 

MANPAGER="vim -M +MANPAGER" man vim

But when do you press `K` in that case? And when is then `ftplugin/zsh.vim` in this case read?

**Comment by chrisbra** [comment]
seems I missed the final `-` part in $MANPAGER. Anyhow, I still don't understand, when you see this issue. If vim is used as manpager, the zsh filetype plugin shouldn't be sourced, right? So how does this happen?

**Comment by chrisbra** [comment]
I am guessing here. Does this fix it:

```patch
diff --git a/ftplugin/zsh.vim b/ftplugin/zsh.vim
index 741f31b..e89396b 100644
--- a/ftplugin/zsh.vim
+++ b/ftplugin/zsh.vim
@@ -20,7 +20,7 @@ let b:undo_ftplugin = "setl com< cms< fo< "

 if executable('zsh')
  if !has('gui_running') && executable('less')
-   command! -buffer -nargs=1 RunHelp silent exe '!zsh -ic "autoload -Uz run-help; run-help <args> 2>/dev/null | LESS= less"' | redraw!
+   command! -buffer -nargs=1 RunHelp silent exe '!MANPAGER= zsh -ic "autoload -Uz run-help; run-help <args> 2>/dev/null | LESS= less"' | redraw!
  elseif has('terminal')
    command! -buffer -nargs=1 RunHelp silent exe ':term zsh -ic "autoload -Uz run-help; run-help <args>"'
  else
```

**Comment by danielshahaf** [comment]
Christian Brabandt wrote on Tue, 19 May 2020 10:19 -0700:
> seems I missed the final `-` part in $MANPAGER. Anyhow, I still don't understand, when you see this issue. If vim is used as manpager, the zsh filetype plugin shouldn't be sourced, right? So how does this happen?
> 

My understanding of the report is:

Run «MANPAGER="vim -M +MANPAGER -" vim =(<<<'ls')».  Set ft=zsh if it's not already set (by filetype.vim).  Press «K» in normal mode.  That'll invoke run-help, which would invoke man in turn, which would invoke a second vim.

I haven't tried this myself.

**Comment by benknoble** [comment]
Ok, here's a simpler (and pretty portable) test-case:

```
$ export MANPAGER='vim -M +MANPAGER -'
$ printf '%s\n' ls > afile.zsh
$ vim afile.zsh
```

At this point, assuming you have at least `filetype plugin on`, the local value of `keywordprg` will be the `:RunHelp` command (I think we all agree here).

Press `K` when the cursor is over `ls`.

When I do this, it will trigger `:RunHelp ls` as expected, which for me barfs all over the screen: the issue seems to be that `run-help`s stdout (the output from running `run-help`, which is the same as running `man`, which is going to end being vim because of `MANPAGER`...) gets piped into `less`, which is like trying to read termcap (?) sequences as if they were file contents.

I guess you could unset `MANPAGER`, effectively overriding anything the user has setup; is it not possible to just `run-help` directly and then redraw? I tried

```
silent exec '!zsh -ic "autoload -Uz run-help ; run-help ls"'
```

but then after quitting the new vim (from `run-help ls`) I had to use `fg` to get back into my original instance, which had mysteriously been backgrounded... very odd indeed.

**Comment by danielshahaf** [comment]
> but then after quitting the new vim (from `run-help ls`) I had to use `fg` to get back into my original instance, which had mysteriously been backgrounded... very odd indeed.

Might this be a zsh bug?  Compare these recent reports:

[workers/45814](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=45814)
[workers/45828](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=45828)

(two others are referenced from the 45814 thread)

**Comment by benknoble** [comment]
@danielshahaf Yeah looks like _that_ part is the same bug. The original problem (termcap garbage piped into less) is hopefully unrelated.

**Comment by danielshahaf** [comment]
@benknoble Thanks.  About the "Vim got backgrounded" part, a patch was posted [in the reply to workers/45828 (workers/45837)](http://www.zsh.org/cgi-bin/mla/redirect?WORKERNUMBER=45837).  If you happen to have a minute to test it and confirm whether it fixes the problem / regresses anything, that'd be great.

Back on topic, I have two datapoints to offer:

1. There doesn't seem to be anything in the manual about whether `run-help` is/isn't expected to do its own paging (in the sense of `$PAGER`).

2. The helper functions `run-help-svn` and `run-help-svk` are one-liners that explicitly do their own paging.
