### ISSUE TITLE
Please update syntax/zsh.vim

### ISSUE THREAD

**Issue by Jun-T** [chrisbra/vim-zsh#3]
Dear Christian Brabandt,

I have a few requests for syntax/zsh.vim.

(1) A new module zsh/param/private is added in zsh 5.2.
The module (loaded by default) includes a new builtin 'private',
which can be used similarly as 'typeset', 'local', etc. Please
add 'private' to zshTypes:

    syn keyword zshTypes    float integer local typeset declare private

(2) Two new options 'appendcreate' and 'globstarshort' are added
recently. Please add the following to zshOptions:

appendcreate
append_create
noappendcreate
no_append_create

globstarshort
glob_star_short
noglobstarshort
no_glob_star_short

(3) (this is optional and you may ignore)
Although it is impossible to include all the possibilities in zshOptions
(since underscore '_' can be inserted anywhere in the option names),
I think it would be better to include all the option names listed in the
"Option Index" of the zsh manual:
http://zsh.sourceforge.net/Doc/Release/Options-Index.html#Options-Index

The following are the option names which are in the Index but not in
zshOptions:

always_last_prompt
auto_cd
bad_pattern
bg_nice
c_bases
cdable_vars
csh_nullcmd
function_argzero
no_always_last_prompt
no_auto_cd
no_bad_pattern
no_bg_nice
no_c_bases
no_cdable_vars
no_csh_nullcmd
no_function_argzero
no_posix_argzero
no_rc_expand_param
no_rematch_pcre
no_traps_async
no_typeset_silent
posix_argzero
rc_expand_param
rematch_pcre
traps_async
typeset_silent

If you want to create a list of option names in the Index, you can
use the following script (topdir is the top of the zsh source tree):

    #!/bin/zsh
    topdir=/path/to/zsh-x.x.x
    grep '^pindex([A-Za-z_]*)$' $topdir/Src/Doc/Zsh/options.yo |
    while read opt
    do
        echo ${${(L)opt#pindex\(}%\)}
    done

TIA
Jun-ichi Takimoto

**Comment by chrisbra** [comment]
Hi Jun-ichi!

Thanks, I have included your changes.

Best,
Christian

On Fr, 25 Dez 2015, Jun-ichi TAKIMOTO wrote:

> Dear Christian Brabandt,
> 
> I have a few requests for syntax/zshvim
> 
> (1) A new module zsh/param/private is added in zsh 52
> The module (loaded by default) includes a new builtin 'private',
> which can be used similarly as 'typeset', 'local', etc Please
> add 'private' to zshTypes:
> 
>     syn keyword zshTypes    float integer local typeset declare private
> 
> (2) Two new options 'appendcreate' and 'globstarshort' are added
> recently Please add the following to zshOptions:
> 
> appendcreate
> append_create
> noappendcreate
> no_append_create
> 
> globstarshort
> glob_star_short
> noglobstarshort
> no_glob_star_short
> 
> (3) (this is optional and you may ignore)
> Although it is impossible to include all the possibilities in zshOptions
> (since underscore '_' can be inserted anywhere in the option names),
> I think it would be better to include all the option names listed in the
> "Option Index" of the zsh manual:
> http://zshsourceforgenet/Doc/Release/Options-Indexhtml#Options-Index
> 
> The following are the option names which are in the Index but not in
> zshOptions:
> 
> always_last_prompt
> auto_cd
> bad_pattern
> bg_nice
> c_bases
> cdable_vars
> csh_nullcmd
> function_argzero
> no_always_last_prompt
> no_auto_cd
> no_bad_pattern
> no_bg_nice
> no_c_bases
> no_cdable_vars
> no_csh_nullcmd
> no_function_argzero
> no_posix_argzero
> no_rc_expand_param
> no_rematch_pcre
> no_traps_async
> no_typeset_silent
> posix_argzero
> rc_expand_param
> rematch_pcre
> traps_async
> typeset_silent
> 
> If you want to create a list of option names in the Index, you can
> use the following script (topdir is the top of the zsh source tree):
> 
>     #!/bin/zsh
>     topdir=/path/to/zsh-xxx
>     grep '^pindex([A-Za-z_]*)$' $topdir/Src/Doc/Zsh/optionsyo |
>     while read opt
>     do
>         echo ${${(L)opt#pindex\(}%\)}
>     done
> 
> TIA
> Jun-ichi Takimoto
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/chrisbra/vim-zsh/issues/3

Liebe Grüße
Christian
-- 
Vernünftiges und Unvernünftiges haben gleichen Widerspruch zu 
erleiden.
		-- Goethe, Maximen und Reflektionen, Nr. 584
