### ISSUE TITLE
zsh comment breaks highlighting in arithmetic mode

### ISSUE THREAD

**Issue by saadparwaiz1** [chrisbra/vim-zsh#31]
Here's how it currently looks like:

![Screenshot 2020-11-19 at 21 40 13](https://user-images.githubusercontent.com/73385353/99727712-4a0e6480-2ab0-11eb-92e6-7994961d330f.jpg)

Here's how it should look like:
![Screenshot 2020-11-19 at 21 40 53](https://user-images.githubusercontent.com/73385353/99727778-5692bd00-2ab0-11eb-830f-a5236f348921.jpg)

**Comment by danielshahaf** [comment]
In general, the insides of `((…))` and `${foo[…]}` are implicitly double-quoted. See http://zsh.sourceforge.net/Doc/Release/Arithmetic-Evaluation.html#Arithmetic-Evaluation for the former.

`[[` may or may not be similarly affected (I can't test that right now). There `#` would be a one-character string.

Workaround: `(( $# == 0 ))`.

**Comment by chrisbra** [comment]
I am confused as I am not a zsh expert.

Is `$(( ))` any different than `(( ))` ? So in other words does this change fix it:

```patch
diff --git a/syntax/zsh.vim b/syntax/zsh.vim
index 80098fc..2445433 100644
--- a/syntax/zsh.vim
+++ b/syntax/zsh.vim
@@ -363,7 +363,7 @@ exe 'syn region  zshSubst       matchgroup=zshSubstDelim transparent start=/\$(/
 syn region  zshParentheses      transparent start='(' skip='\\)' end=')' fold
 syn region  zshGlob             start='(#' end=')'
 syn region  zshMathSubst        matchgroup=zshSubstDelim transparent
-                                \ start='\$((' skip='\\)' end='))'
+                                \ start='\$\?((' skip='\\)' end='))'
                                 \ contains=zshParentheses,@zshSubst,zshNumber,
                                 \ @zshDerefs,zshString keepend fold
 " The ms=s+1 prevents matching zshBrackets several times on opening brackets
```

**Comment by saadparwaiz1** [comment]
I don't think there is any difference between the two, I generally put a `$` in front to get the output of `(())`

**Comment by chrisbra** [comment]
okay, than that patch should be okay

**Comment by danielshahaf** [comment]
Not at keyboard, but a few edge cases that might be run into:

First, `((` is only valid at command position, never in the middle of a word, whereas `echo foo$((bar))baz` _is_ valid. (This difference is exactly like `(…)` (subshells) v. `$(…)` (command substitution).) Consequently, there are some syntaxes that are resemble math but aren't:

- `cat foo<((echo hello world))` - process substitution
- `:; ((echo hello world); (echo lorem ipsum))` - nested subshells

There's also a syntax with ambiguous parsing:

- `(( (git-ls-files)<=(sh -c /foo) ))` - it's either a 3-deep nested subshell with stdin redirection from a process substitution, or an arithmetic evaluation, but I don't remember which.

I'm _not_  saying that these should all be handled. On the contrary: zsh itself didn't handle the second and third ones until recently, and they all have easy workarounds. That said, adding a `[<=>]\@<!` after the `\$\?` would address the first, and I don't see anything it'd break.

Second, I question the (preëxisting) `skip=…`. IIRC, `(( ((foo + bar)) ))` is valid, in which case the `skip=…` should be replaced with a balanced-parentheses idiom. This would, of course, be a separate issue.

**Comment by danielshahaf** [comment]
Sorry, I see now the balanced parentheses handling is already there. (I didn't see it until now.)

**Comment by chrisbra** [comment]
thanks, adjusted it accordingly.
