### ISSUE TITLE
run-help is aliased to `man`

### ISSUE THREAD

**Issue by dotrakoun-sqsp** [chrisbra/vim-zsh#34]
the keywordprg doesn't work for me
`run-help` is aliased to `man` by default (see `zshcontrib(1)`)
you need to `unalias run-help` before autoloading the module that defines the fn

**Comment by chrisbra** [comment]
Hm, for me, `unalias run-help`  returns "no such alias". Also shouldn't `autoload -U run-help` take care of this?

**Comment by danielshahaf** [comment]
The `autoload` declares a function also named `run-help` but doesn't remove the eponymous alias, so it'll still be expanded in contexts that expand aliases, such as interactive shells.

Try passing `-o noaliases` to zsh or stopping passing `-i` to zsh. Excuse brevity.

**Comment by chrisbra** [comment]
yeah, so let's remove the `-i` flag than.
