### ISSUE TITLE
Single quotes inside parameter substitution inside double quotes

### ISSUE THREAD

**Issue by Parranoh** [chrisbra/vim-zsh#35]
Consider this example:

```zsh
var="${var//pattern/'}"
```

The `'` is quoted by the double quotes. Therefore escaping it with a `\` is not a valid workaround because that would substitute `\'` instead of `'`.

It is however interpreted not as part of the string inside double quotes but rather as the beginning of a new string inside single quotes, resulting in this:

![image](https://user-images.githubusercontent.com/6516678/123491000-e89a0f80-d615-11eb-980c-9eb5ecec23d8.png)

I know for this particular example I could leave out the double quotes entirely, but that would not be true in a more complex scenario like this:

```zsh
var="${var//pattern/'} $othervar"
```

**Comment by danielshahaf** [comment]
For anyone else running into this, here's one workaround:

```zsh
local sq="'"
var="${var//pattern/$sq}"
```

**Comment by chrisbra** [comment]
hm, that doesn't seem to be easily fixable...

**Comment by chrisbra** [comment]
can you please check the following patch?

```patch
diff --git a/syntax/zsh.vim b/syntax/zsh.vim
index a9bd7f5..d80b61f 100644
--- a/syntax/zsh.vim
+++ b/syntax/zsh.vim
@@ -373,8 +373,8 @@ syn region  zshBrackets         contained transparent start='{'ms=s+1 skip='\\}'
                                 \ end='}' fold
 exe 'syn region  zshBrackets    transparent start=/{/ms=s+1 skip=/\\}/ end=/}/ contains='.s:contained. ' fold'

-syn region  zshSubst            matchgroup=zshSubstDelim start='\${' skip='\\}'
-                                \ end='}' contains=@zshSubst,zshBrackets,zshQuoted,zshString fold
+syn region  zshSubst            matchgroup=zshSubstDelim start='\${' skip='['"]\\|\\}'
+                                \ end='}' contains=@zshSubst,zshBrackets,zshQuoted fold
 exe 'syn region  zshOldSubst    matchgroup=zshSubstDelim start=/`/ skip=/\\[\\`]/ end=/`/ contains='.s:contained. ',zshOldSubst fold'

 syn sync    minlines=50 maxlines=90
```

**Comment by Parranoh** [comment]
It works in my particular case, but it doesn't highlight the string in these examples anymore:

```zsh
${var/pattern/'replacement'}
${var/pattern/"replacement"}
```

Before the patch:
![image](https://user-images.githubusercontent.com/6516678/123558377-2a51c400-d796-11eb-99dc-938dea94ed41.png)

After:
![image](https://user-images.githubusercontent.com/6516678/123558407-58cf9f00-d796-11eb-9db2-c0301034597e.png)

**Comment by Parranoh** [comment]
Doing some further testing, apparently zsh seems to be doing some rather wacky (at least in my opinion) stuff with double quotes inside parameter substitution without complaining about whitespace or mismatched braces:

```zsh
var='stuff_pattern_stuff'
"${var/pattern/ repl " }' " }"  # stuff_ repl  }' _stuff
```

This one however does not parse, complaining about a missing double-quote, a missing brace, and another missing double-quote:

```zsh
"${var/pattern/repl"}
```

To me, it seems like in the first case a new double-quoted string is opened by the second `"` right after `repl`, like it was not already inside a double-quoted string. Unlike the original example where the `'` does not open a string because it is inside a double-quoted string.

Not sure if this is helpful in any way with the matter at hand, but it seems like these are some testcases that would break most highlighters for zsh; they do break [zdharma's](https://github.com/zdharma/fast-syntax-highlighting).

**Comment by chrisbra** [comment]
> ${var/pattern/'replacement'}

That is actually contradictory to the first example. Either we accept and allow string based highlighting or not.

**Comment by danielshahaf** [comment]
@chrisbra, @Parranoh is saying that single quoting is permitted when the parameter expansion stands alone but not when it's double quoted: `print -r -- ${foo/bar/'}` ≠ `print -r -- "${foo/bar/'}"`.

That might be documented in <https://zsh.sourceforge.io/Doc/Release/Expansion.html#Rules>. If neefed, we can ask the mailing list for clarifications, too.

**Comment by Parranoh** [comment]
Yes, Daniel is right. In `"${var/pat/'}"` the `'` has no special meaning and should not be highlighted. In `${var/pat/'repl'}` the `'` do have a special meaning because they delimit a string and should thus be highlighted. Sorry if I was unclear before.

**Comment by lacygoill** [comment]
I think we need 2 rules.  One for quoted subtitutions; and another for non-quoted ones.
```diff
diff --git a/syntax/zsh.vim b/syntax/zsh.vim
index bab89b9..511dfc9 100644
--- a/syntax/zsh.vim
+++ b/syntax/zsh.vim
@@ -48,7 +48,7 @@ syn match   zshPOSIXQuoted      '\\u[0-9a-fA-F]\{1,4}'
 syn match   zshPOSIXQuoted      '\\U[1-9a-fA-F]\{1,8}'
 
 syn region  zshString           matchgroup=zshStringDelimiter start=+"+ end=+"+
-                                \ contains=zshQuoted,@zshDerefs,@zshSubst fold
+                                \ contains=zshQuoted,@zshDerefs,@zshSubstQuoted fold
 syn region  zshString           matchgroup=zshStringDelimiter start=+'+ end=+'+ fold
 syn region  zshPOSIXString      matchgroup=zshStringDelimiter start=+\$'+
                                 \ skip=+\\[\\']+ end=+'+ contains=zshPOSIXQuoted,zshQuoted
@@ -158,7 +158,11 @@ syn match   zshNumber           '[+-]\=\d\+\.\d\+\>'
 
 " TODO: $[...] is the same as $((...)), so add that as well.
 syn cluster zshSubst            contains=zshSubst,zshOldSubst,zshMathSubst
+syn cluster zshSubstQuoted      contains=zshSubstQuoted,zshOldSubst,zshMathSubst
 exe 'syn region  zshSubst       matchgroup=zshSubstDelim transparent start=/\$(/ skip=/\\)/ end=/)/ contains='.s:contained. '  fold'
+exe 'syn region  zshSubstQuoted matchgroup=zshSubstDelim transparent start=/\$(/ skip=/\\)/ end=/)/ contains='.s:contained. '  fold'
+syn region  zshSubstQuoted      matchgroup=zshSubstDelim start='\${' skip='\\}'
+  \ end='}' contains=@zshSubst,zshBrackets,zshQuoted fold
 syn region  zshParentheses      transparent start='(' skip='\\)' end=')' fold
 syn region  zshGlob             start='(#' end=')'
 syn region  zshMathSubst        matchgroup=zshSubstDelim transparent
@@ -223,6 +227,7 @@ hi def link zshTypes            Type
 hi def link zshSwitches         Special
 hi def link zshNumber           Number
 hi def link zshSubst            PreProc
+hi def link zshSubstQuoted      zshSubst
 hi def link zshMathSubst        zshSubst
 hi def link zshOldSubst         zshSubst
 hi def link zshSubstDelim       zshSubst
```
