### ISSUE TITLE
Far behind sh/bash

### ISSUE THREAD

**Issue by xeruf** [chrisbra/vim-zsh#37]
When editing a zsh script in neovim I get much richer syntax highlighting using the `sh` or `bash` filetype. Isn't this somehow based on `sh`? Is this related to neovim?

**Comment by chrisbra** [comment]
First of all, shell language is very complex. I do not intend to allow to color every possible obscure shell language feature. Look at the default shell syntax file that comes with vim/neovim and at the same time, how many different bug reports are opened. So a simpler zsh syntax is actually a feature. However, if you are missing something specific, please let me know and I see if I can support this.

**Comment by xeruf** [comment]
Here is an illustration:

![ft=zsh](https://user-images.githubusercontent.com/13354331/128924802-ac3c2267-e26a-4bc4-a482-edef0e80b8d7.png)

![ft=sh](https://user-images.githubusercontent.com/13354331/128924879-1004cda8-c41f-466a-9791-f1212e613337.png)

`sh` highlights alias & function definitions, as well as commands and flags separately, which I would expect the zsh highlighting to do as well.

**Comment by chrisbra** [comment]
wow, that is very shiny and in my opinion a bit too much. 

Having said that, I am not against enhancing the current syntax script, but we need to be very careful, not to introduce regressions while keeping it fast and performant. 

So I'll leave that to someone who wants to actually spend time on it, I am open for PRs. I personally don't feel comfortable making those adjustments :(

**Comment by xeruf** [comment]
My expectation would be that `zsh` is exactly the same as `sh` or `bash` with tiny adjustments for `zsh`-specific syntax if needed. From my quick testing it seems that `bash` and `sh` are essentially equivalent as well.

**Comment by xeruf** [comment]
Aha!

File: ftplugin/bash.vim
```vim
" Vim filetype plugin file
" Language: bash
" Maintainer:   Bram Moolenaar
" Last Changed: 2019 Jan 12
"
" This is not a real filetype plugin.  It allows for someone to set 'filetype'
" to "bash" in the modeline, and gets the effect of filetype "sh" with
" b:is_bash set.  Idea from Mahmode Al-Qudsi.

if exists("b:did_ftplugin")
  finish
endif

unlet! b:is_sh
unlet! b:is_kornshell
let b:is_bash = 1

runtime! ftplugin/sh.vim ftplugin/sh_*.vim ftplugin/sh/*.vim
```

**Comment by danielshahaf** [comment]
> So I'll leave that to someone who wants to actually spend time on it, I am open for PRs.

Then reopen this issue?

**Comment by danielshahaf** [comment]
> Here is an illustration:

FWIW, I think I like this.

It would be interesting to compare that and zsh-syntax-highlighting's defaults: for instance, default highlighting of delimiter quotes and lack of highlighting of command words. (I'm not unaffiliated.)

**Comment by xeruf** [comment]
Yes, it would be great to somewhat unify these different tools, Emacs highlighting could be another place to look.

**Comment by danielshahaf** [comment]
Somewhat related: https://github.com/zsh-users/zsh-syntax-highlighting/issues/327. That issue imagined other parser consumers would be written in zsh, as opposed to VimL/elisp, but I'm putting it here for context (and in the hope that one day it'll turn out to be the proverbial apple that falls on an unsuspecting head).
