### ISSUE TITLE
Globbing flags break highlighting and folding.

### ISSUE THREAD

**Issue by lucc** [chrisbra/vim-zsh#6]
Globbing flags are described in zshexpn(1). As an example take this test file:
```zsh
#!/bin/zsh
function bar () {
  [[ $1 = (#i)test ]]
}
function foo () {
  bar
  ls *(#l)
}
a=(
  1
  2
)
echo "the end"
```
The highlighting error can be seen directly, to see the folding error you can execute `for i in range(1,line('$')) | echo foldlevel(i) ."\t". getline(i) | endfor` in vim.

**Comment by chrisbra** [comment]
Hi Lucas!

On Do, 10 Mär 2016, Lucas Hoffmann wrote:

> Globbing flags are described in zshexpn(1). As an example take this test file:
> ```zsh
> #!/bin/zsh
> function bar () {
>   [[ $1 = (#i)test ]]
> }
> function foo () {
>   bar
>   ls *(#l)
> }
> a=(
>   1
>   2
> )
> echo "the end"
> ```
> The highligting error can be seen directly, to see the folding error you can execute `for i in range(1,line('$')) | echo foldlevel(i) ."\t". getline(i) | endfor` in vim.

Can you check latest HEAD please?

**Comment by lucc** [comment]
Thank you, that fixes the original issue but I think the globing flags are not allowed every where. Maybe the syntax region should be allowed or searched for in certain places (sorry I don't know the terms and internals of vim syntax definitions). But it is already an improvement like this.

**Comment by chrisbra** [comment]
Hi Lucas!

On Do, 10 Mär 2016, Lucas Hoffmann wrote:

> Thank you, that fixes the original issue but I think the globing flags are not allowed every where. Maybe the syntax region should be allowed or searched for in certain places (sorry I don't know the terms and internals of vim syntax definitions). But it is already an improvement like this.

I don't know either exactly. So let's for now just leave it like this. 
However, according to the manpage globbing flags need to be in front of 
the pattern, which contradicts your second example.

Liebe Grüße
Christian
-- 
Was ist der Akademiker anders, als ein eingelerntes und angeeignetes
Glied einer großen Vereinigung?
		-- Johann Wolfgang von Goethe (an Zelter, 1832)
