### ISSUE TITLE
Highlighting in "complex" variable expansion

### ISSUE THREAD

**Issue by anntzer** [chrisbra/vim-zsh#7]
Currently, zsh.vim highlights `${foo:-bar}` (and similar constructs) in a single color, even though the second term is not a variable but a string.  Compare with the default sh.vim, which correctly does not highlight the second term as a variable.

**Comment by chrisbra** [comment]
I appreciate a patch

**Comment by chrisbra** [comment]
I looked into the sh.vim default syntax highlighting and I think it is way too complex. (also notice by how many bugs there are reported against the vim/vim repository). So let's keep it simple and keep it the way it is currently.
