### ISSUE TITLE
"((#foo))" is highlighted as comment after foo

### ISSUE THREAD

**Issue by blueyed** [chrisbra/vim-zsh#9]
Using `((#foo))` instead of `(( $#foo ))` triggers highlighting as comment.

**Comment by blueyed** [comment]
The same applies to

```zsh
    m=((../)#Makefile(N))
```

**Comment by chrisbra** [comment]
oh well, I don't intend to support every obscure feature from the zsh language. But if a patch is written, I might include.

**Comment by blueyed** [comment]
I see.
Just wanted to file the issue here, so we have test cases when coming back to fix it.. :)
